version: '3.7'

services: 
  database:
    container_name: docker-local-mysql
    image: mysql:5.7
    volumes:
      - "./data:/var/lib/mysql"
    restart: always
    ports: 
      - 3306:3306
    environment:
      MYSQL_DATABASE: mesaC2s
      MYSQL_ROOT_PASSWORD: mesa
    command: mysqld --init-file="./setup/install_db.sql"